env: "local"

database:
  host: "db"
  port: 5432
  databaseName: "todo"
  user: "todo_manager"
  password: "1488"

http_server:
  address: "0.0.0.0:8069"
  timeout: 5s
  iddle_timeout: 60s

migrationPath: "/app/restapi/migration" # Path to migration files in Unix systems