services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo_manager
      POSTGRES_PASSWORD: 1488
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_manager -d todo"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      CONFIG_PATH: /app/restapi/config/config.yaml
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: todo_manager
      DB_PASSWORD: 1488
      DB_NAME: todo
    ports:
      - "8069:8069"
      
volumes:
  db-data: